export enum ProductList {
  PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST',
  PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS',
  PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL',
}

export enum ProductDetails {
  PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST',
  PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS',
  PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'
}

export enum IndicaList {
  INDICA_LIST_REQUEST = 'INDICA_LIST_REQUEST',
  INDICA_LIST_SUCCESS = 'INDICA_LIST_SUCCESS',
  INDICA_LIST_FAIL = 'INDICA_LIST_FAIL'
}

export enum SativaList {
  SATIVA_REQUEST = 'SATIVA_REQUEST',
  SATIVA_SUCCESS = 'SATIVA_SUCCESS',
  SATIVA_FAIL = 'SATIVA_FAIL'
}