export enum ProductList {
  PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST',
  PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS',
  PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL',
}

export enum ProductDetails {
  PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST',
  PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS',
  PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'
}

export enum ProductDelete {
  PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST',
  PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS',
  PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'
}

export enum ProductUpdate {
  PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST',
  PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS',
  PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
}

export enum IndicaList {
  INDICA_LIST_REQUEST = 'INDICA_LIST_REQUEST',
  INDICA_LIST_SUCCESS = 'INDICA_LIST_SUCCESS',
  INDICA_LIST_FAIL = 'INDICA_LIST_FAIL'
}

export enum SativaList {
  SATIVA_REQUEST = 'SATIVA_REQUEST',
  SATIVA_SUCCESS = 'SATIVA_SUCCESS',
  SATIVA_FAIL = 'SATIVA_FAIL'
}