export enum USER {
  USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST',
  USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS',
  USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL',

  USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST',
  USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS',
  USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL',

  USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST',
  USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS',
  USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL'
}